---
# tasks file for ./roles/looking-glass

- name: Install podman.
  ansible.builtin.package:
    name: podman
    state: present

- name: Build looking glass container. 
  containers.podman.podman_container:
    name: lg
    path: ./files
    build:
      format: docker