---
# tasks file for ./roles/looking-glass

- name: added in 2.4, previously you used 'include'
  import_tasks: redhat.yml
  when: ansible_facts['os_family']|lower == 'redhat'
  
- name: Download latest version of looking-glass.
  get_url:                                                           
    url: "https://looking-glass.io/artifact/{{ version }}/source"                       
    dest: "{{WRKDIR}}/looking-glass.tar.gz"

- name: Unarchive a file that is already on the remote machine
  ansible.builtin.unarchive:
    src: "{{WRKDIR}}/looking-glass.tar.gz"
    dest: "/usr/local/src/"
    remote_src: yes

- name: Make looking glass compile path.
  file:
    path: "/usr/local/src/looking-glass-{{ version }}/client/build"
    state: directory

- name: Compile and install looking glass 
  command: "chdir=/usr/local/src/looking-glass-{{ version }}/client/build {{ item }}"
  with_items:
  - cmake ../ 
  - make  
  - make install